# Build settings and site core config
[build]
  base = "/"
  command = "yarn build"
  publish = "build"
  functions = "api"

# Environmental variables and optional secrets
[build.environment]
    CI="false" # Set CI to false, to prevent warnings from exiting the build
    name = "APT_INSTALL_COMMANDS"
    value = "apt-get update && apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2"

# Redirect the /api/* path to the lambda functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 301
  force = true

# For router history mode, ensure pages land on index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  

# Plugins
[[plugins]]
package = "netlify-plugin-chromium"
  [plugins.inputs]
  packageManager = "yarn"

# Set any security headers here
[[headers]]
  for = "/*"
  [headers.values]
  # Uncomment to enable Netlify user control. Requires premium plan.
  # Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"